version: '2.1'
services:
  hostap:
    network_mode: host
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.template
    image: betothreeprod/hapwizpy-%%BALENA_MACHINE_NAME%%
    env_file: 
      - common.env
      - .env
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    volumes:
      - hostapcache:/var/cache/hostap
  wifi-connect:
    network_mode: host
    build:
      context: ./python-wifi-connect
      dockerfile: Dockerfile.template
    image: betothreeprod/python-wifi-connect
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    privileged: true
    ports:
      - "80:80"
volumes:
  hostapcache:
