version: '2.1'
services:
  hostap:
    network_mode: host
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.template
    image: betothreeprod/hapwizpy
    env_file: common.env
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    volumes:
      - hostapcache:/var/cache/hostap
volumes:
  hostapcache:
