version: '2'
services:
  wifi-spot:
    network_mode: host
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.template
    image: betothreeprod/hapwizpy-%%BALENA_MACHINE_NAME%%
    env_file:
      - common.env
      - .env
    privileged: true
    labels:
      io.balena.features.dbus: "1"
    volumes:
      - hostapd:/etc/hostapd
      - hapwizard:/etc/hapwizard
      - wifi-connect:/usr/src/python-wifi-connect/
      - netplan:/etc/netplan
    depends_on:
      - wifi-box
    cap_add:
      - ALL
  wifi-box:
    network_mode: host
    build:
      context: ./python-wifi-connect
      dockerfile: Dockerfile.template
    image: betothreeprod/python-wifi-connect-%%BALENA_MACHINE_NAME%%
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.supervisor-api: "1"
    privileged: true
    ports:
      - "80:80"
    volumes:
      - wifi-connect:/usr/src/app/
volumes:
  hostapd:
  hapwizard:
  wifi-connect:
  netplan:
