version: '2'
services:
  wifi-spot:
    network_mode: host
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.armhf
    image: betothreeprod/hapwizpy-raspberrypi3
    env_file:
      - common.env
      - .env
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - hostapd:/etc/hostapd
      - hapwizard:/etc/hapwizard
      - wifi-connect:/usr/src/python-wifi-connect/
  wifi-box:
    network_mode: host
    build:
      context: ./python-wifi-connect
      dockerfile: Dockerfile.armhf
    image: betothreeprod/python-wifi-connect-raspberrypi3
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    privileged: true
    ports:
      - "80:80"
    volumes:
      - wifi-connect:/usr/src/app/
volumes:
  hostapd:
  hapwizard:
  wifi-connect:
