version: '2.1'
services:
  hostapd:
    network_mode: host
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.armhf
    image: betothreeprod/hapwizpy-armhf
    env_file: common.env
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    volumes:
      - hostapcache:/var/cache/hostap
volumes:
  hostapcache:
