version: 2.1
orbs:
  shellcheck: circleci/shellcheck@1.3.16
jobs:
  compose:
    docker:
    - image: betothreeprod/intel-nuc-node-php7
    shell: /bin/bash -leo pipefail
    environment:
    - BASH_ENV: /etc/profile
    - DKR_ARCH: x86_64
    steps:
    - checkout
    - run:
        command: git submodule sync
    - run:
        command: git submodule update --init --recursive
    - restore_cache:
        key: v1-dependencies-{{ checksum "package-lock.json" }}
    - run:
        name: Install dependencies
        command: |
          npm install --no-optional
          npm link balena-cloud
    - setup_remote_docker:
        docker_layer_caching: false
    - save_cache:
        key: v1-dependencies-{{ checksum "package-lock.json" }}
        paths:
        - node_modules
    - run:
        name: Set architecture and Setup Environment Variables
        command: |
          ./deploy.sh $DKR_ARCH --nobuild --exit
    - run:
        command: |
          set -u
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker-compose -f docker-compose.$DKR_ARCH build
    - persist_to_workspace:
        root: .
        paths:
        - node_modules
workflows:
  cleanup:
    jobs:
    - shellcheck/check:
        ignore: 'SC1091'
  build-and-compose:
    jobs:
    - compose:
        context: Info-b23prodtm
  version: 2
